AUCTION_ITEM_CATEGORY_GENERAL = 1
AUCTION_ITEM_CATEGORY_ELECTRONICS = 2
AUCTION_ITEM_CATEGORY_MEDIA = 3
AUCTION_ITEM_CATEGORY_CLOTHING = 4

AUCTION_ITEM_CATEGORY_CHOICES = (
    (AUCTION_ITEM_CATEGORY_ELECTRONICS, 'Electronics'),
    (AUCTION_ITEM_CATEGORY_MEDIA, 'Media'),
    (AUCTION_ITEM_CATEGORY_CLOTHING, 'Clothing'),
    (AUCTION_ITEM_CATEGORY_GENERAL, 'General'),
)

AUCTION_ITEM_STATUS_IDLE = 1
AUCTION_ITEM_STATUS_RUNNING = 2
AUCTION_ITEM_STATUS_ON_HOLD = 3
AUCTION_ITEM_STATUS_SOLD = 4
AUCTION_ITEM_STATUS_EXPIRED = 5
AUCTION_ITEM_STATUS_DISPUTED = 6

AUCTION_ITEM_STATUS_CHOICES = (
    (AUCTION_ITEM_STATUS_IDLE, 'Idle'),
    (AUCTION_ITEM_STATUS_RUNNING, 'Running'),
    (AUCTION_ITEM_STATUS_ON_HOLD, 'On Hold'),
    (AUCTION_ITEM_STATUS_SOLD, 'Sold'),
    (AUCTION_ITEM_STATUS_EXPIRED, 'Expired'),
    (AUCTION_ITEM_STATUS_DISPUTED, 'Disputed'),
)

AUCTION_EVENT_SHIPPING_USPS = 1
AUCTION_EVENT_SHIPPING_FEDEX = 2
AUCTION_EVENT_SHIPPING_UPS = 3
AUCTION_EVENT_SHIPPING_DHL = 4  

AUCTION_EVENT_SHIPPING_CHOICES = (
    (AUCTION_EVENT_SHIPPING_USPS, 'USPS'),
    (AUCTION_EVENT_SHIPPING_FEDEX, 'FedEx'),
    (AUCTION_EVENT_SHIPPING_UPS, 'UPS'),
    (AUCTION_EVENT_SHIPPING_DHL, 'DHL'),
)

AUCTION_ITEM_CONDITION_USED = 1
AUCTION_ITEM_CONDITION_USED_LIKE_NEW = 2
AUCTION_ITEM_CONDITION_NEW = 3

AUCTION_ITEM_CONDITION_CHOICES = (
    (AUCTION_ITEM_CONDITION_USED, 'Used'),
    (AUCTION_ITEM_CONDITION_USED_LIKE_NEW, 'Used Like New'),
    (AUCTION_ITEM_CONDITION_NEW, 'New'),
)

SALES_PAYMENT_STATUS_PROCESSING = 1
SALES_PAYMENT_STATUS_CLEARED = 2
SALES_PAYMENT_STATUS_DISPUTED = 3
SALES_PAYMENT_STATUS_REFUNDED = 4

SALES_PAYMENT_STATUS_CHOICES = (
    (SALES_PAYMENT_STATUS_PROCESSING, 'Processing'),
    (SALES_PAYMENT_STATUS_CLEARED, 'Cleared'),
    (SALES_PAYMENT_STATUS_DISPUTED, 'Disputed'),
    (SALES_PAYMENT_STATUS_REFUNDED, 'Refunded'),
)

AUCTION_EVENT_SORTING_TITLE = 'title'
AUCTION_EVENT_SORTING_CONDITION = 'condition'
AUCTION_EVENT_SORTING_PRICE_ASC = 'price_asc'
AUCTION_EVENT_SORTING_PRICE_DESC = 'price_desc'
AUCTION_EVENT_SORTING_END_TIME_ASC = 'end_time_asc'
AUCTION_EVENT_SORTING_END_TIME_DESC = 'end_time_desc'
AUCTION_EVENT_SORTING_CHOICES = (
    (AUCTION_EVENT_SORTING_TITLE, 'item__title'),
    (AUCTION_EVENT_SORTING_CONDITION, 'item__condition'),
    (AUCTION_EVENT_SORTING_PRICE_ASC, 'starting_price'),
    (AUCTION_EVENT_SORTING_PRICE_DESC, '-starting_price'),
    (AUCTION_EVENT_SORTING_END_TIME_ASC, 'end_time'),
    (AUCTION_EVENT_SORTING_END_TIME_DESC, '-end_time'),
)